openai_api_key : sk-99999999999999999999999999999999999999
history_file: ./history.md
chatgpt_config:
  model: gpt-3.5-turbo # gpt-3.5-turbo or gpt-4
  max_tokens: 1000
  temperature: 1
  top_p: 1
  timeout: 300 # seconds